### ISSUE TITLE
UserEntity not mapped to UserInterface

### ISSUE THREAD

**Issue by Ruesa18** [whatwedo/CrudBundle#113]
I did not configure the CRUD-Bundle so that it should use the default configuration (Therefore I also have no wwd-specific YAML-file under config/packages). But my User-Entity did not get integrated correctly.

Error: `An exception has been thrown during the rendering of a template ("Class 'whatwedo\TableBundle\Entity\UserInterface' does not exist").`

The following code snippet solved the Issue for me (Thanks @tuxes3 )
```yaml
doctrine:
    orm:
        resolve_target_entities:
            # The class which will be returned with "Symfony\Component\Security\Core\Security::getUser"
            whatwedo\TableBundle\Entity\UserInterface: App\Entity\User
```
